
package com.document.style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldDocStyleImplService", targetNamespace = "http://style.document.com/", wsdlLocation = "http://localhost:9993/whateverurl/helodoc?wsdl")
public class HelloWorldDocStyleImplService
    extends Service
{

    private final static URL HELLOWORLDDOCSTYLEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDDOCSTYLEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWORLDDOCSTYLEIMPLSERVICE_QNAME = new QName("http://style.document.com/", "HelloWorldDocStyleImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9993/whateverurl/helodoc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDDOCSTYLEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWORLDDOCSTYLEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWorldDocStyleImplService() {
        super(__getWsdlLocation(), HELLOWORLDDOCSTYLEIMPLSERVICE_QNAME);
    }

    public HelloWorldDocStyleImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDDOCSTYLEIMPLSERVICE_QNAME, features);
    }

    public HelloWorldDocStyleImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDDOCSTYLEIMPLSERVICE_QNAME);
    }

    public HelloWorldDocStyleImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDDOCSTYLEIMPLSERVICE_QNAME, features);
    }

    public HelloWorldDocStyleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldDocStyleImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldDocStyleIface
     */
    @WebEndpoint(name = "HelloWorldDocStyleImplPort")
    public HelloWorldDocStyleIface getHelloWorldDocStyleImplPort() {
        return super.getPort(new QName("http://style.document.com/", "HelloWorldDocStyleImplPort"), HelloWorldDocStyleIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldDocStyleIface
     */
    @WebEndpoint(name = "HelloWorldDocStyleImplPort")
    public HelloWorldDocStyleIface getHelloWorldDocStyleImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://style.document.com/", "HelloWorldDocStyleImplPort"), HelloWorldDocStyleIface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDDOCSTYLEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDDOCSTYLEIMPLSERVICE_EXCEPTION;
        }
        return HELLOWORLDDOCSTYLEIMPLSERVICE_WSDL_LOCATION;
    }

}
