package com.subra;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-15T19:42:25.899-04:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "HelloEtcServiceService", 
                  wsdlLocation = "file:/C:/Users/sdass/workspace/eclipse/mars/axis-cxf-calc-client/WebContent/wsdl/helloetcservice.wsdl",
                  targetNamespace = "http://subra.com/") 
public class HelloEtcServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://subra.com/", "HelloEtcServiceService");
    public final static QName HelloEtcServicePort = new QName("http://subra.com/", "HelloEtcServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/sdass/workspace/eclipse/mars/axis-cxf-calc-client/WebContent/wsdl/helloetcservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloEtcServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/sdass/workspace/eclipse/mars/axis-cxf-calc-client/WebContent/wsdl/helloetcservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloEtcServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloEtcServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloEtcServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloEtcServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloEtcServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloEtcServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloEtcService
     */
    @WebEndpoint(name = "HelloEtcServicePort")
    public HelloEtcService getHelloEtcServicePort() {
        return super.getPort(HelloEtcServicePort, HelloEtcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloEtcService
     */
    @WebEndpoint(name = "HelloEtcServicePort")
    public HelloEtcService getHelloEtcServicePort(WebServiceFeature... features) {
        return super.getPort(HelloEtcServicePort, HelloEtcService.class, features);
    }

}
