package com.subra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-15T19:42:25.852-04:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://subra.com/", name = "HelloEtcService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloEtcService {

    @WebMethod
    @RequestWrapper(localName = "multiply", targetNamespace = "http://subra.com/", className = "com.subra.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://subra.com/", className = "com.subra.MultiplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://subra.com/", className = "com.subra.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://subra.com/", className = "com.subra.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
